# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{analytics_goo}
  s.version = "0.1.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Rob Christie"]
  s.date = %q{2011-06-01}
  s.email = %q{robchristie@gmail.com}
  s.extra_rdoc_files = [
    "README.markdown",
    "TODO"
  ]
  s.files = [
    "CHANGELOG",
    "MIT-LICENSE",
    "README.markdown",
    "Rakefile",
    "TODO",
    "VERSION",
    "analytics_goo.gemspec",
    "autotest/CHANGELOG",
    "autotest/LICENSE",
    "autotest/README.rdoc",
    "autotest/discover.rb",
    "autotest/railsplugin.rb",
    "autotest/railsplugin_rspec.rb",
    "init.rb",
    "lib/analytics_goo.rb",
    "lib/analytics_goo/google_analytics_adapter.rb",
    "rails/init.rb",
    "tasks/analytics_goo.rake",
    "test/analytics_goo_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/eyestreet/analytics_goo}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{AnalyticsGoo provides server side non-javascript tracking using google analytics.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

